# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-06 12:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaveUnicaUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_num', models.BigIntegerField()),
                ('run_dv', models.CharField(max_length=1)),
                ('run_type', models.CharField(max_length=3)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='claveunicauser',
            unique_together=set([('run_num', 'run_dv', 'run_type')]),
        ),
        migrations.AlterIndexTogether(
            name='claveunicauser',
            index_together=set([('run_num', 'run_dv', 'run_type')]),
        ),
    ]
