# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-25 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('claveunica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaveUnicaUserCourseRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_num', models.BigIntegerField()),
                ('run_dv', models.CharField(max_length=1)),
                ('run_type', models.CharField(max_length=3)),
                ('course', opaque_keys.edx.django.models.CourseKeyField(max_length=255)),
                ('mode', models.TextField(choices=[(b'audit', b'audit'), (b'honor', b'honor')])),
                ('auto_enroll', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterIndexTogether(
            name='claveunicausercourseregistration',
            index_together=set([('run_num', 'run_dv', 'run_type')]),
        ),
    ]
