# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-04-08 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claveunica', '0002_auto_20191125_1839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claveunicauser',
            options={'permissions': [('is_staff_guest', 'Can View claveunica/info/export')]},
        ),
    ]
